//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.03 at 09:49:26 AM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://it.camp.pl/countries")
package pl.camp.it.countries;
